2019-05-02 15:01:42,216 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 16:00:02,977 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 16:00:20,860 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 16:56:18,527 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 16:57:08,146 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 16:58:41,332 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-02 17:15:21,122 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:06:13,735 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:12:40,225 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:15:40,332 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:24:29,599 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:47:30,522 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:49:09,887 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-03 14:50:25,322 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:44]
2019-05-04 13:32:12,284 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 13:56:52,963 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 13:58:47,709 ERROR: Exception on /reset_password_request [POST] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/app/routes.py", line 156, in reset_password_request
    send_password_reset_email(user)
  File "/home/pi/microblog/app/email.py", line 13, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2019-05-04 14:00:29,503 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:00:44,311 ERROR: Exception on /reset_password_request [POST] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/app/routes.py", line 156, in reset_password_request
    send_password_reset_email(user)
  File "/home/pi/microblog/app/email.py", line 19, in send_password_reset_email
    user=user, token=token))
  File "/home/pi/microblog/app/email.py", line 29, in send_email
    Thread(target=send_asyns_email, args=(app, msg)).start()
NameError: name 'Thread' is not defined
2019-05-04 14:01:35,418 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:01:50,616 ERROR: Exception on /reset_password_request [POST] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/app/routes.py", line 156, in reset_password_request
    send_password_reset_email(user)
  File "/home/pi/microblog/app/email.py", line 20, in send_password_reset_email
    user=user, token=token))
  File "/home/pi/microblog/app/email.py", line 30, in send_email
    Thread(target=send_asyns_email, args=(app, msg)).start()
NameError: name 'send_asyns_email' is not defined
2019-05-04 14:03:10,703 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:17:24,186 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:22:27,035 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:34:25,081 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:36:17,118 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:37:23,463 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:39:57,924 ERROR: Exception on /reset_password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NTY5OTU2NTMuOTk5ODc2LCJyZXNldF9wYXNzd29yZCI6M30.GXjvLgJJDSEcxmZR140m88y3I_w-hNfmkj10f6_2RsY [GET] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/app/routes.py", line 174, in reset_password
    return redenr_template('reset_password.html', form=form)
NameError: name 'redenr_template' is not defined
2019-05-04 14:41:03,254 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 14:41:48,286 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTY5OTU4OTIuMDY0MDk5OCwicmVzZXRfcGFzc3dvcmQiOjN9.CWGzbbzhoVO9O0HTUF0-VJeXUZT6dRQQiKxgMSbbaGg [GET] [in /home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/microblog/venv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/microblog/app/routes.py", line 174, in reset_password
    return rendenr_template('reset_password.html', form=form)
NameError: name 'rendenr_template' is not defined
2019-05-04 14:42:19,452 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:46]
2019-05-04 15:05:04,758 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:48]
2019-05-04 15:13:53,982 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:50]
2019-05-04 15:17:48,699 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:50]
2019-05-04 15:22:13,093 INFO: Microblog startup [in /home/pi/microblog/app/__init__.py:50]
